-- dietary_recommendation.sql
-- Table for dietary recommendations for mothers
CREATE TABLE dietary_recommendation (
  id SERIAL PRIMARY KEY,
  source_id VARCHAR(64) UNIQUE,
  title VARCHAR NOT NULL,
  swahili_name VARCHAR,
  content TEXT NOT NULL,
  description TEXT,
  target_group VARCHAR,
  target_groups JSONB NOT NULL DEFAULT '[]'::jsonb,
  trimester_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  meal_type VARCHAR(64),
  meal_time VARCHAR(32),
  key_nutrients JSONB NOT NULL DEFAULT '[]'::jsonb,
  health_benefits JSONB NOT NULL DEFAULT '[]'::jsonb,
  preparation_tips TEXT,
  cautions JSONB NOT NULL DEFAULT '[]'::jsonb,
  nutrition_highlight VARCHAR(255),
  portion_guide TEXT,
  image_suggestion VARCHAR(255),
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  calories INTEGER,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  source_name VARCHAR,
  created_by INTEGER REFERENCES users(id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
